#Requires -Version 5.1
<#
.SYNOPSIS
    Standalone uninstaller for GitHub RDP Mega Toolkit.
.DESCRIPTION
    Reverses all actions performed by install.ps1:
      * Removes the install directory
      * Removes the install dir from system PATH
      * Removes Start Menu + Desktop shortcuts
      * Removes the registry uninstaller entry under HKLM
      * Optionally cleans up app data under "$env:LOCALAPPDATA\GitHubRDPToolkit"
.PARAMETER InstallDir
    Install directory to remove. Defaults to "$env:ProgramFiles\GitHubRDPToolkit".
.PARAMETER RemoveAppData
    Also remove cached data under "$env:LOCALAPPDATA\GitHubRDPToolkit".
.EXAMPLE
    .\uninstall.ps1
.EXAMPLE
    .\uninstall.ps1 -RemoveAppData
.NOTES
    This script can be invoked directly from the source tree, or from the
    copy generated by install.ps1 at the install location.
#>
[CmdletBinding()]
param(
    [string]$InstallDir = (Join-Path $env:ProgramFiles 'GitHubRDPToolkit'),
    [switch]$RemoveAppData
)

$ErrorActionPreference = 'Stop'

$Script:AppName       = 'GitHubRDPToolkit'
$Script:AppVersion    = '9.0.0'
$Script:UninstallKey  = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\GitHubRDPToolkit'

function Write-Step  { param([string]$m) Write-Host "[uninstall] $m" -ForegroundColor Cyan }
function Write-OK    { param([string]$m) Write-Host "[ok]        $m" -ForegroundColor Green }
function Write-Warn2 { param([string]$m) Write-Host "[warn]      $m" -ForegroundColor Yellow }
function Write-Err2  { param([string]$m) Write-Host "[error]     $m" -ForegroundColor Red }

function Test-Administrator {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Invoke-SelfElevate {
    Write-Warn2 'Administrator rights required. Relaunching elevated...'
    $argsList = @("-NoProfile", "-ExecutionPolicy", "Bypass", "-File", "`"$PSCommandPath`"", "-InstallDir", "`"$InstallDir`"")
    if ($RemoveAppData) { $argsList += '-RemoveAppData' }
    try {
        $p = Start-Process -FilePath 'powershell.exe' -Verb RunAs -Wait -PassThru -ArgumentList $argsList
        exit $p.ExitCode
    } catch {
        Write-Err2 "Elevation declined or failed: $($_.Exception.Message)"
        exit 1
    }
}

# ----------------------------------------------------------------------
# Pre-flight: self-elevate
# ----------------------------------------------------------------------
if (-not (Test-Administrator)) {
    Invoke-SelfElevate
    return
}

Write-Host ''
Write-Host '======================================' -ForegroundColor White
Write-Host "  GitHub RDP Mega Toolkit Uninstaller" -ForegroundColor White
Write-Host '======================================' -ForegroundColor White
Write-Host ''
Write-Step "Install dir: $InstallDir"

# ----------------------------------------------------------------------
# Remove PATH entry
# ----------------------------------------------------------------------
Write-Step 'Removing install dir from system PATH...'
$machinePath = [Environment]::GetEnvironmentVariable('PATH', 'Machine')
if ($machinePath) {
    $entries = $machinePath.Split(';', [StringSplitOptions]::RemoveEmptyEntries) | Where-Object { $_ -ne $InstallDir }
    $newPath = $entries -join ';'
    [Environment]::SetEnvironmentVariable('PATH', $newPath, 'Machine')
    Write-OK 'PATH entry removed (open a new shell to see the change).'
} else {
    Write-Warn2 'No system PATH set; skipping.'
}

# ----------------------------------------------------------------------
# Remove Start Menu shortcuts
# ----------------------------------------------------------------------
Write-Step 'Removing Start Menu shortcuts...'
$startMenuDir = Join-Path ([Environment]::GetFolderPath('CommonPrograms')) $Script:AppName
if (Test-Path $startMenuDir) {
    Remove-Item -Recurse -Force $startMenuDir
    Write-OK "Removed: $startMenuDir"
} else {
    Write-Warn2 "Start Menu folder not found: $startMenuDir"
}

# ----------------------------------------------------------------------
# Remove Desktop shortcut
# ----------------------------------------------------------------------
Write-Step 'Removing Desktop shortcut...'
$desktopLnk = Join-Path ([Environment]::GetFolderPath('CommonDesktopDirectory')) "$($Script:AppName).lnk"
if (Test-Path $desktopLnk) {
    Remove-Item -Force $desktopLnk
    Write-OK "Removed: $desktopLnk"
} else {
    Write-Warn2 "Desktop shortcut not found: $desktopLnk"
}

# ----------------------------------------------------------------------
# Remove registry uninstaller entry
# ----------------------------------------------------------------------
Write-Step 'Removing registry uninstaller entry...'
if (Test-Path $Script:UninstallKey) {
    Remove-Item -Recurse -Force $Script:UninstallKey
    Write-OK "Removed registry key: $Script:UninstallKey"
} else {
    Write-Warn2 "Registry uninstaller entry not found: $Script:UninstallKey"
}

# ----------------------------------------------------------------------
# Remove install directory
# ----------------------------------------------------------------------
Write-Step "Removing install directory: $InstallDir"
if (Test-Path $InstallDir) {
    try {
        Remove-Item -Recurse -Force $InstallDir
        Write-OK "Install directory removed: $InstallDir"
    } catch {
        Write-Err2 "Failed to remove install directory: $($_.Exception.Message)"
        Write-Warn2 'Some files may be in use. Close any open shells and retry.'
    }
} else {
    Write-Warn2 "Install directory not found: $InstallDir"
}

# ----------------------------------------------------------------------
# Optionally remove app data
# ----------------------------------------------------------------------
if ($RemoveAppData) {
    $appData = Join-Path $env:LOCALAPPDATA $Script:AppName
    Write-Step "Removing app data: $appData"
    if (Test-Path $appData) {
        try {
            Remove-Item -Recurse -Force $appData
            Write-OK "App data removed: $appData"
        } catch {
            Write-Warn2 "Could not fully remove app data: $($_.Exception.Message)"
        }
    } else {
        Write-Warn2 "No app data found at: $appData"
    }
}

# ----------------------------------------------------------------------
# Done
# ----------------------------------------------------------------------
Write-Host ''
Write-Host '======================================' -ForegroundColor Green
Write-Host '  Uninstall complete!' -ForegroundColor Green
Write-Host '======================================' -ForegroundColor Green
Write-Host ''
exit 0
