# =============================================================================
# rdp-toolkit.bash — Bash completion for the RDP Mega Toolkit v9 CLI.
#
# Install:
#   sudo cp scripts/completions/rdp-toolkit.bash /etc/bash_completion.d/rdp-toolkit
#   # or, per-user:
#   cp scripts/completions/rdp-toolkit.bash ~/.local/share/bash-completion/completions/rdp-toolkit
#   source ~/.bashrc
#
# Generated by hand to mirror rdp_toolkit/cli.py:build_parser(). Update both
# files together when adding a subcommand or a flag.
# =============================================================================

# Subcommand list — must match cli.py build_parser() sub.add_parser() calls.
_rdp_toolkit_subcommands="install start stop status connect config tunnel vm rotate kill doctor"

# Per-subcommand flag sets — kept as separate variables for readability.
_rdp_toolkit_global_flags="-h --help -V --version"

_rdp_toolkit_install_flags="--platform -h --help"
_rdp_toolkit_install_platforms="kali windows android ubuntu"

_rdp_toolkit_start_flags="--hours --profile -h --help"
_rdp_toolkit_start_profiles="productivity gaming minimal"

_rdp_toolkit_stop_flags="-h --help"
_rdp_toolkit_status_flags="-h --help"
_rdp_toolkit_connect_flags="-h --help"

_rdp_toolkit_config_flags="--platform -h --help"
_rdp_toolkit_config_platforms="kali windows android ubuntu"

_rdp_toolkit_tunnel_actions="list status test"
_rdp_toolkit_tunnel_providers="serveo localhost.run cloudflare localtunnel all"

_rdp_toolkit_vm_actions="start stop shell"
_rdp_toolkit_vm_names="kali ubuntu windows"

_rdp_toolkit_rotate_flags="-h --help"
_rdp_toolkit_kill_targets="all"

_rdp_toolkit_doctor_flags="-h --help"

# Main completion function.
_rdp_toolkit() {
    local cur prev words cword
    _init_completion || {
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    }

    # Global flags are always available.
    if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "$_rdp_toolkit_global_flags" -- "$cur"))
        return 0
    fi

    # First word after `rdp-toolkit` is the subcommand.
    if [ "$cword" -eq 1 ]; then
        COMPREPLY=($(compgen -W "$_rdp_toolkit_subcommands" -- "$cur"))
        return 0
    fi

    # Subcommand-specific completion.
    local subcmd="${words[1]}"
    case "$subcmd" in
        install)
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_install_flags" -- "$cur"))
            elif [[ "$prev" == "--platform" ]]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_install_platforms" -- "$cur"))
            fi
            ;;
        start)
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_start_flags" -- "$cur"))
            elif [[ "$prev" == "--profile" ]]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_start_profiles" -- "$cur"))
            elif [[ "$prev" == "--hours" ]]; then
                # Suggest common durations.
                COMPREPLY=($(compgen -W "1 2 4 6" -- "$cur"))
            fi
            ;;
        stop | status | doctor)
            COMPREPLY=($(compgen -W "$_rdp_toolkit_global_flags -h --help" -- "$cur"))
            ;;
        connect)
            # Connect takes an optional run_id (numeric). No completion.
            ;;
        config)
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_config_flags" -- "$cur"))
            elif [[ "$prev" == "--platform" ]]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_config_platforms" -- "$cur"))
            fi
            ;;
        tunnel)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_tunnel_actions" -- "$cur"))
            elif [ "$cword" -eq 3 ] && [[ "${words[2]}" == "test" ]]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_tunnel_providers" -- "$cur"))
            fi
            ;;
        vm)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_vm_actions" -- "$cur"))
            elif [ "$cword" -eq 3 ]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_vm_names" -- "$cur"))
            fi
            ;;
        rotate)
            # rotate takes an optional run_id.
            ;;
        kill)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=($(compgen -W "$_rdp_toolkit_kill_targets" -- "$cur"))
            fi
            ;;
    esac
    return 0
}

# Register for both `rdp-toolkit` (the installed binary) and `rdp_toolkit`
# (the python -m form).
complete -F _rdp_toolkit rdp-toolkit
complete -F _rdp_toolkit rdp_toolkit
