#!/usr/bin/env bash
# setup-termux.sh — Install RDP Mega Toolkit on Termux (Android)
# Usage:  bash setup-termux.sh
set -euo pipefail

PKG_NAME="rdp-toolkit"
VERSION="9.0.0"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SRC_DIR="${PROJECT_ROOT}/rdp_toolkit"
PREFIX_DIR="${PREFIX:-/data/data/com.termux/files/usr}"
BIN_DIR="${PREFIX_DIR}/bin"
LIB_DIR="${PREFIX_DIR}/share/rdp-toolkit"
CONFIG_DIR="${HOME}/.config/rdp-toolkit"

# ----- detect Termux --------------------------------------------------------
if [ -z "${TERMUX_VERSION:-}" ] && [ ! -d "/data/data/com.termux" ]; then
    echo "ERROR: This script must be run inside Termux (Android)." >&2
    echo "       Install Termux from https://termux.dev/ and re-run." >&2
    exit 1
fi

echo "[setup] Detected Termux: ${TERMUX_VERSION:-unknown}"
echo "[setup] PREFIX:  ${PREFIX_DIR}"
echo "[setup] HOME:    ${HOME}"
echo

# ----- update + install packages -------------------------------------------
echo "[setup] Updating package lists..."
pkg update -y

echo "[setup] Installing runtime packages..."
pkg install -y python openssh freerdp

# freerdp on Termux provides xfreerdp — make sure it's reachable
if ! command -v xfreerdp >/dev/null 2>&1 && ! command -v xfreerdp2 >/dev/null 2>&1; then
    echo "[setup] WARNING: xfreerdp not found. RDP sessions may not work." >&2
    echo "[setup]          Try: pkg install freerdp" >&2
fi

# ----- python deps ----------------------------------------------------------
echo "[setup] Installing Python dependencies..."
pip install --upgrade pip
pip install pyyaml

# ----- stage application ----------------------------------------------------
echo "[setup] Installing ${PKG_NAME} into ${LIB_DIR}/ ..."
rm -rf "${LIB_DIR}"
mkdir -p "${LIB_DIR}"
cp -a "${SRC_DIR}" "${LIB_DIR}/rdp_toolkit"

# ----- launcher wrapper -----------------------------------------------------
WRAPPER="${BIN_DIR}/rdp-toolkit"
echo "[setup] Writing launcher: ${WRAPPER}"
cp "${SCRIPT_DIR}/rdp-toolkit.sh" "${WRAPPER}"
chmod 0755 "${WRAPPER}"

# Re-write wrapper to point at the installed lib dir
cat > "${WRAPPER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by setup-termux.sh
export PYTHONPATH="${LIB_DIR}:\${PYTHONPATH:-}"
exec python3 -m rdp_toolkit "\$@"
EOF
chmod 0755 "${WRAPPER}"

# ----- config dir -----------------------------------------------------------
echo "[setup] Creating config directory: ${CONFIG_DIR}"
mkdir -p "${CONFIG_DIR}/sessions" "${CONFIG_DIR}/tunnels" "${CONFIG_DIR}/logs"
if [ ! -f "${CONFIG_DIR}/config.yaml" ]; then
    cat > "${CONFIG_DIR}/config.yaml" <<EOF
# RDP Mega Toolkit v${VERSION} - default config
version: "${VERSION}"
platform: "android"
tunnel:
  priority: ["serveo", "localhost.run", "cloudflare", "localtunnel"]
rdp:
  default_port: 3389
notify:
  enabled: true
EOF
    echo "[setup] Wrote default config to ${CONFIG_DIR}/config.yaml"
fi

# ----- bash completion (Termux supports it) --------------------------------
if [ -d "${PREFIX_DIR}/share/bash-completion/completions" ]; then
    cat > "${PREFIX_DIR}/share/bash-completion/completions/rdp-toolkit" <<'EOF'
_rdp_toolkit_completion() {
    local cur words
    cur="${COMP_WORDS[COMP_CWORD]}"
    words="doctor config tunnel vm rdp session start stop status notify --help --version"
    COMPREPLY=( $(compgen -W "${words}" -- "${cur}") )
}
complete -F _rdp_toolkit_completion rdp-toolkit
EOF
    echo "[setup] Installed bash completion."
fi

echo
echo "=================================================="
echo " ${PKG_NAME} v${VERSION} installed!"
echo "=================================================="
echo " Run: rdp-toolkit doctor"
echo
echo " Config:   ${CONFIG_DIR}"
echo " Library:  ${LIB_DIR}"
echo " Launcher: ${WRAPPER}"
echo "=================================================="
